# Generated by Django 4.2.16 on 2024-11-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
