# Generated by Django 4.2.16 on 2024-11-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_reservation_pickup_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='caption',
        ),
    ]
