# Generated by Django 4.2.16 on 2024-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='daily_rate',
        ),
        migrations.AddField(
            model_name='car',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
