# Generated by Django 4.2.16 on 2024-10-24 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_price_per_day_car_daily_rate_car_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
