# Generated by Django 4.2.16 on 2024-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_reservation_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
