# Generated by Django 4.2.16 on 2024-10-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
