# Generated by Django 4.2.16 on 2024-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_end_datetime_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancellation_notified',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_source_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('pick up', 'Pick Up'), ('van', 'Van'), ('mini van', 'Mini Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
