# Generated by Django 4.2.16 on 2024-10-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_reservation_cancellation_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='unavailable_units',
            field=models.IntegerField(default=0),
        ),
    ]
