# Generated by Django 4.2.16 on 2024-10-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_quantity_car_total_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='start_datetime',
        ),
    ]
