# Generated by Django 4.2.16 on 2024-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_car_options_car_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
