# Generated by Django 4.2.16 on 2024-10-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_notified',
            field=models.BooleanField(default=False),
        ),
    ]
