# Generated by Django 4.2.16 on 2024-10-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_reservation_payment_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
