# Generated by Django 4.2.16 on 2024-10-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_reservation_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
